on:
  workflow_call:
    inputs:
      python_version:
        type: string
        required: false
        default: '3.9'
    outputs:
      env_list:
        value: ${{ jobs.set-matrix.outputs.env_list }}
      environments:
        value: ${{ jobs.set-matrix.outputs.environments }}

jobs:
  set-matrix:
    name: Environments
    runs-on: ubuntu-latest
    outputs:
      env_list: ${{ steps.create-matrix.outputs.env_list }}
      environments: ${{ steps.create-matrix.outputs.environments }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}

    - name: Execute generate_config.py
      id: create-matrix
      run: |
        python .github/scripts/generate_config.py > script_output.txt
        cat script_output.txt
        ENV_LIST=$(tail -n 1 script_output.txt | jq -c '.')
        if [ -z "$ENV_LIST" ] || [ "$ENV_LIST" == "{}" ]; then
          echo "Error: No environments found in the output"
          exit 1
        fi
        ENVIRONMENTS=$(echo $ENV_LIST | jq -r 'keys | join(",")')
        echo "env_list=$ENV_LIST" >> $GITHUB_OUTPUT
        echo "environments=$ENVIRONMENTS" >> $GITHUB_OUTPUT

    - name: Debug output
      run: |
        echo "Generated environment list:"
        echo "${{ steps.create-matrix.outputs.env_list }}"
        echo "Environments: ${{ steps.create-matrix.outputs.environments }}"
        echo "Git status:"
        git status
        echo "Git log:"
        git log --oneline -n 5
        echo "Directory structure:"
        tree -L 4 workloads