name: "deploy"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions: write-all

jobs:

  create-matrix:
    name: Set Matrix
    uses: ./.github/workflows/create-matrix.yml@v1


  Plan:
    needs: [create-matrix]
    name: Terraform Plan - ${{ matrix.environment }}
    strategy:
      max-parallel: 4
      matrix:
        environment: ["dev", "staging", "production"]
    uses: ../terraform-plan.yml
    secrets: inherit
    with:
      environment: ${{ matrix.environment }}
      region: ${{fromJson(needs.set-matrix.outputs.matrix)[matrix.environment].region }}
      role_to_assume: ${{fromJson(needs.set-matrix.outputs.matrix)[matrix.environment].env_role }}

  Apply:
    needs: [ Plan, create-matrix ]
    name: Terraform Apply - ${{ matrix.environment }}
    strategy:
      max-parallel: 1
      matrix:
        environment: ["dev", "staging", "production"]
    uses: ../terraform-apply.yml
    secrets: inherit
    with:
      environment: ${{ matrix.environment }}
      region: ${{fromJson(needs.set-matrix.outputs.matrix)[matrix.environment].region }}
      role_to_assume: ${{fromJson(needs.set-matrix.outputs.matrix)[matrix.environment].env_role }}
