name: "deploy"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions: write-all

jobs:
  create-matrix:
    name: Set Matrix
    uses: ./.github/workflows/create-matrix.yml

  Plan:
    needs: [create-matrix]
    name: Plan - ${{ matrix.class }}/${{ matrix.environment }}/${{ matrix.region }}
    strategy:
      max-parallel: 4
      matrix: ${{ fromJson(needs.create-matrix.outputs.matrix) }}
    uses: ./.github/workflows/terraform-plan.yml
    secrets: inherit
    with:
      environment: ${{ matrix.environment }}
      class: ${{ matrix.class }}
      region: ${{ matrix.region }}
      role_to_assume: ${{ matrix.env_role }}
      tf_backend_bucket: "terraform-state-bucket-12345"

  Apply:
    needs: [Plan, create-matrix]
    name: Terraform Apply - ${{ matrix.path }}
    strategy:
      max-parallel: 1
      matrix: ${{ fromJson(needs.create-matrix.outputs.matrix) }}
    uses: ./.github/workflows/terraform-apply.yml
    secrets: inherit
    with:
      environment: ${{ matrix.environment }}
      region: ${{ matrix.region }}
      role_to_assume: ${{ matrix.env_role }}